name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! If this is your first time reporting a bug, please read our [guide](https://jasp-stats.org/2018/03/29/request-feature-report-bug-jasp/) first.
  - type: dropdown
    id: jasp-version
    attributes:
      label: JASP Version
      description: What version of JASP are you running?
      options:
        - Others
        - 0.9.2
        - 0.12
        - 0.13
        - 0.13.1
        - 0.14
        - 0.15
        - 0.16
        - 0.16.1
        - 0.16.2
        - 0.16.3
        - 0.16.4
    validations:
      required: true
  - type: input
    id: commit-id
    attributes:
      label: Commit ID
      description: If you are using a nightly build, please mention the commit hash.
      placeholder: "e9f3d9f223ff67345d3613381b3c3ebc70de142f"
    validations:
      required: false
  - type: dropdown
    id: jasp-module
    attributes:
      label: JASP Module
      description:  What JASP analysis are you seeing the problem on?
      multiple: true
      options:
        - No Module
        - ANOVA
        - Audit
        - Bain
        - Circular
        - Descriptives
        - Distributions
        - Equivalence T-Tests
        - Factor
        - Frequencies
        - JAGS
        - Learn Bayes
        - Machine Learning
        - Meta Analysis
        - Mixed Models
        - Network
        - Process Control
        - Prophet
        - Regression
        - Reliability
        - SEM
        - Summary Statistics
        - T-Tests
        - Visual Modeling
        - Other
    validations:
      required: false
  - type: input
    id: jasp-analysis
    attributes:
      label: What analysis are you seeing the problem on?
      description: Please mention the name of the analysis or method that the causes the issue.
      placeholder: "One Sample T-Test"
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      description: Please mention the name and version of the Operation System that you are using?
      multiple: true
      options:
        - Windows 10
        - Windows 11
        - macOS Intel
        - macOS Silicon
        - Linux
        - Flatpak
        - Ubuntu
        - Debian
        - Fedora
        - Arch
        - Manjaro
        - PopOs
        - Other
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: |
        Please tell us what happened.
        
        Note: You can attach images or log files by clicking this area to highlight it and then dragging files in. If you upload a JASP file, you need to compress your .jasp-file before uploading it to GitHub (aka as a .zip-file). In addition, if you would prefer to not make your data publicly available, you can send your files directly to us, issues@jasp-stats.org.
      placeholder: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: Please tell us what should have happened instead of the bug. In addition, you can include any images or files showcasing the correct behaviour.
      placeholder: "This should have happened instead!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Can you reproduce the bug? If so, please let us know what steps you take to reproduce this bug.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log (if any)
      description:
        Please upload your Log files by dropping them into the area below, and add any information notes if necessary.
        
        **Read our [Logging Guide](https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/user-guide/logging-howto.md) page to learn where to (and how to) find JASP log files.**
  - type: checkboxes
    id: final-checklist
    attributes:
      label: Final Checklist
      description: Please take a moment and make sure that you have filled all fields as accurately as possible; otherwise, we will not be able to track and resolve your issue.
      options:
         - label: I have included a screenshot showcasing the issue, if possible.
           required: false
         - label: I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
           required: false
         - label: I have accurately described the bug, and steps to reproduce it.
           required: false
