name: 'Logger'
on:
  issues:
    types: 
      - opened
      - reopened
      - edited

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: '👋 Thanks for reporting!'
      #       })
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/github-script@v6
        with:
          script: console.log(context)
